export const browserCoreExamples = [
  "quantclaw browser status",
  "quantclaw browser start",
  "quantclaw browser stop",
  "quantclaw browser tabs",
  "quantclaw browser open https://example.com",
  "quantclaw browser focus abcd1234",
  "quantclaw browser close abcd1234",
  "quantclaw browser screenshot",
  "quantclaw browser screenshot --full-page",
  "quantclaw browser screenshot --ref 12",
  "quantclaw browser snapshot",
  "quantclaw browser snapshot --format aria --limit 200",
  "quantclaw browser snapshot --efficient",
  "quantclaw browser snapshot --labels",
];

export const browserActionExamples = [
  "quantclaw browser navigate https://example.com",
  "quantclaw browser resize 1280 720",
  "quantclaw browser click 12 --double",
  'quantclaw browser type 23 "hello" --submit',
  "quantclaw browser press Enter",
  "quantclaw browser hover 44",
  "quantclaw browser drag 10 11",
  "quantclaw browser select 9 OptionA OptionB",
  "quantclaw browser upload /tmp/quantclaw/uploads/file.pdf",
  'quantclaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "quantclaw browser dialog --accept",
  'quantclaw browser wait --text "Done"',
  "quantclaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "quantclaw browser console --level error",
  "quantclaw browser pdf",
];
